SWIG = swig -c++ -python
GCC = g++ -O3 -fPIC

# The following directory may be difference in difference machines. To find the correct one in your machine, do "locate Python.h" #
IDIR = /usr/custom/Anaconda-2.0.1/include/python2.7/

.PHONY: all
all: _VBBinaryLensingLibrary.so

%_wrap.cxx: %.i
	$(SWIG) $^

%_wrap.o: %_wrap.cxx
	$(GCC) -lm -c $^ -I $(IDIR)

%.o: %.cpp
	$(GCC) -lm -c $^

_%.so: %.o %_wrap.o
	$(GCC) -shared $^ -o $@

.PHONY: clean
clean:
	$(RM) $(PROJECT)
	$(RM) *.so *.pyc *_wrap.cxx *.o
